language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -n --standard=phpcs.xml ./
  - vendor/bin/php-cs-fixer --diff --dry-run -vv fix
  
after_script:
  - vendor/bin/coveralls -v
  
matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
